config/routes.rb
DemoRisks::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
    resources :assignments
  end

  resources :work_loads do
    resources :work_histories 
  end

  resources :sessions,       :only => [:new, :create, :destroy]
  resources :microposts,     :only => [:create, :destroy]
  resources :relationships,  :only => [:create, :destroy]
  resources :contracts
  resources :contract_types, :only => [:new, :create, :index]
  resources :work_load_types, :only => [:new, :create, :index] 

  root :to => 'pages#home'

  match '/signup',   :to => 'users#new'
  match '/signin',   :to => 'sessions#new'
  match '/signout',  :to => 'sessions#destroy'

  match '/about',    :to => 'pages#about'
  match '/contact',  :to => 'pages#contact'
  match '/help',     :to => 'pages#help'

  match '/users/:id/work_loads', :to => 'work_loads#index', :as => :assigned

end

app/models/contract.rb
# == Schema Information
# Schema version: 20101207011704
#
# Table name: contracts
#
#  id               :integer         not null, primary key
#  alias            :string(255)
#  name             :string(255)
#  created_at       :datetime
#  updated_at       :datetime
#  description      :string(255)
#  contract_type_id :integer
#

class Contract < ActiveRecord::Base
  attr_accessible :name, :description, :alias, :contract_type_id

  validates :name,     :presence     => true,
                       :length       => { :maximum => 50 }
  validates :alias,    :presence     => true,
                       :length       => { :within => 1..10 },
                       :uniqueness   => { :case_sensitive => false }

  has_many   :obligations, :dependent => :destroy
  has_many   :work_loads, :through => :obligations
  belongs_to :contract_type

  def type_name
    contract_type.name if contract_type
  end
 
end

app/models/contract_type.rb
# == Schema Information
# Schema version: 20101206005744
#
# Table name: contract_types
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class ContractType < ActiveRecord::Base
  attr_accessible :name

  has_many :contracts
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_filter :authenticate 
  before_filter :authorized_user, :only => [:create, :update, :edit]
  before_filter :admin_user, :only => :destroy

  helper_method :sort_column, :sort_direction


   def new
   @title = "Contracts"
   @contract = Contract.new
  end

  def index
    @title = "Contracts"
    @sort_attributes = "LOWER(" + sort_column + ") " + sort_direction
    @contracts = Contract.find(:all, :include => :contract_type, :order => @sort_attributes)
  end

  def create
    @title = "Contracts"
    @contract = Contract.new(params[:contract])
    if @contract.save
      flash[:notice] = "successfully created Contract."
      redirect_to @contract
    else
      render :action => :new
    end
  end

  def show
   @title = "Show Contracts"
   @contract = Contract.find(params[:id])
  end

  def edit
   @title = "Contracts"
   @contract = Contract.find(params[:id])
  end

  def update
   @title = "Contracts"
     @contract = Contract.find(params[:id])
    if @contract.update_attributes(params[:contract])
      flash[:notice] = "Successfully updated contract."
      redirect_to @contract
    else
      render :action => 'edit'
    end
  end

  def destroy
   @contract.destroy
   flash[:notice] = "Successfully deleted contract."
   redirect_to contracts_path
  end

private

    def admin_user
     if current_user.admin?
       @contract = Contract.find(params[:id])
     else
       flash[:error] = "Not authorized to delete contract. Please contact an administrator"
       redirect_to contracts_path
     end
    end

    def authorized_user
     if current_user.admin? || current_user.manager?
      
     else
       flash[:error] = "Not authorized. Please contact an administrator"
       redirect_to contracts_path
     end
    end

    def sort_column
      Contract.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/_form.html.erb
<%= simple_form_for @contract do |f| %>
<%= f.input :alias %>
<%= f.input :name %>
<%= f.association :contract_type, :include_blank => false %>
<%= f.input :description %>
<%= f.button :submit %>
<% end%>

app/views/contracts/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Show", @contract %> |
  <%= link_to "Delete", @contract, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", contracts_path %>
</p>

app/views/contracts/index.html.erb
<table class="admin">
  <tr>
   <th><%= sortable "type" %></th>
   <th><%= sortable "alias" %></th>
   <th><%= sortable "name" %></th>
   <th><%= sortable "description" %></th>
  </tr>
  <% for contract in @contracts %>
  <tr>
   <td><%= contract.type_name %></td>
   <td><%= contract.alias %></td>
   <td><%= contract.name %></td>
   <td><%= contract.description %></td>
   <td><%= link_to "edit", edit_contract_path(contract) %> | <%= link_to "delete", contract , :method => :delete , :confirm => 'Are you sure?'%></td>
  </tr>
  <% end %>
</table>
<p><%= link_to "New Contract", new_contract_path %></p>

app/views/contracts/show.html.erb
<p>
  <strong>Type:</strong>
  <%= @contract.type_name %>
</p>
<p>
  <strong>Alias:</strong>
  <%= @contract.alias %>
</p>
<p>
  <strong>Name:</strong>
  <%= @contract.name%>
</p>
<p>
  <strong>Description:</strong>
  <%= @contract.description %>
</p>

<p>
  <%= link_to "Edit", edit_contract_path(@contract) %> |
  <%= link_to "View All", contracts_path %>
</p>