config/routes.rb
DemoRisks::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
    resources :assignments
  end

  resources :work_loads do
    resources :work_histories 
  end

  resources :sessions,       :only => [:new, :create, :destroy]
  resources :microposts,     :only => [:create, :destroy]
  resources :relationships,  :only => [:create, :destroy]
  resources :contracts
  resources :contract_types, :only => [:new, :create, :index]
  resources :work_load_types, :only => [:new, :create, :index] 

  root :to => 'pages#home'

  match '/signup',   :to => 'users#new'
  match '/signin',   :to => 'sessions#new'
  match '/signout',  :to => 'sessions#destroy'

  match '/about',    :to => 'pages#about'
  match '/contact',  :to => 'pages#contact'
  match '/help',     :to => 'pages#help'

  match '/users/:id/work_loads', :to => 'work_loads#index', :as => :assigned

end

app/models/work_load.rb
# == Schema Information
# Schema version: 20110126024724
#
# Table name: work_loads
#
#  id                :integer         not null, primary key
#  name              :string(255)
#  alias             :string(255)
#  description       :string(255)
#  probability       :integer
#  impact            :integer
#  priority          :string(255)
#  status            :string(255)
#  percent_complete  :integer
#  resolution_effort :decimal(, )
#  work_load_type_id :integer
#  requested_date    :date
#  expected_date     :date
#  completed_date    :date
#  created_at        :datetime
#  updated_at        :datetime
#  estimate          :decimal(, )
#

class WorkLoad < ActiveRecord::Base
    attr_accessible :name, :alias, :description, :probability, :impact, :contract_ids, :user_ids, :status, :percent_complete, :resolution_effort, :work_load_type_id, :requested_date, :expected_date, :completed_date, :estimate

   has_many :obligations, :dependent => :destroy
   has_many :contracts, :through => :obligations
   has_many :assignments, :dependent => :destroy
   has_many :users, :through => :assignments, :validate => false  
   has_many :work_histories
   belongs_to :work_load_type    

  validates :name,     		:presence     => true,
                       		:length       => { :maximum => 50 },
		       		:uniqueness   => { :case_sensitive => false }
 
  validates :alias,    		:presence     => true,
                       		:length       => { :within => 1..10 },
                       		:uniqueness   => { :case_sensitive => false }

  validates :probability,    	:numericality => true,
                                :inclusion    => { :in => 0..5 }
  
  validates :impact,    	:numericality => true,
	                        :inclusion    => { :in => 0..5 }
  
  validates :percent_complete,	:numericality => true,
  				:inclusion    => { :in => 0..100 }
  
  validates :resolution_effort,	:numericality => true
  
  validates :status,		:inclusion    => { :in => %w(Inactive Active Closed Cancelled)}                    		

  before_save :set_priority, :set_completed_date
  
  def set_resolution_effort
       self.resolution_effort = WorkHistory.sum(:effort, :conditions => ['work_load_id = ?', self.id])
       self.save
  end


  private
    
    def  set_priority
      prio = self.probability * self.impact
      if (20..25).include?(prio)
         self.priority = "A"
      elsif (15..19).include?(prio)
         self.priority = "B"
      elsif (8..14).include?(prio)
         self.priority = "C"
      else
         self.priority = "D"
      end
    end

    def set_completed_date
     if self.status_changed? && (self.status == "Closed" || self.status == "Cancelled") 
        self.completed_date = Date.today
     elsif self.status_changed? && self.percent_complete < 100 && (self.status == "Active" || self.status == "Inactive")
         self.completed_date = nil
     end
    end

    def self.search(search)
       if search
         where('name LIKE ?', "%#{search}%")
       else
         scoped
       end
    end

 end

app/models/work_load_type.rb
# == Schema Information
# Schema version: 20101220021835
#
# Table name: work_load_types
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class WorkLoadType < ActiveRecord::Base
  attr_accessible :name

  has_many :work_loads
end

app/controllers/work_loads_controller.rb
class WorkLoadsController < ApplicationController

  before_filter :authenticate 
  before_filter :authorized_user, :only => [:create, :update, :edit]
  before_filter :admin_user, :only => :destroy

  helper_method :sort_column, :sort_direction

  def new
   @work_load = WorkLoad.new
   new_form_defaults
  end

  def index
   @sort_attributes = "LOWER(" + sort_column + ") " + sort_direction
   #@contracts = WorkLoad.find(:all, :order => @sort_attributes)
   if params[:id]
   	@work_loads = User.find_by_id(params[:id]).work_loads.search(params[:search]).order(@sort_attributes).paginate(:per_page => 5, :page => params[:page])
   else
	#@work_loads = WorkLoad.find(:all, :order => @sort_attributes).paginate(:per_page => 5, :page => params[:page])
        @work_loads = WorkLoad.search(params[:search]).order(@sort_attributes).paginate(:per_page => 5, :page => params[:page])
   end
   
  end

  def create
   @work_load = WorkLoad.new(params[:work_load])
    if @work_load.save 
      flash[:success] = "Workload Created"
      redirect_to @work_load
    else
      @title = "Create Work"
      render :new
    end
  end

  def destroy
   @work_load.destroy
   flash[:notice] = "Successfully deleted work load."
   redirect_to work_loads_path
  end

  def show
   @work_load = WorkLoad.find(params[:id])
   @work_load_type = WorkLoadType.find_by_id(@work_load.work_load_type_id)
   if @work_load_type
      @work_load_type_name = @work_load_type.name
   else
      @work_load_type_name = nil
   end
   if @work_load.estimate.to_f > 0.1
    @percent_complete = @work_load.resolution_effort.to_f / @work_load.estimate.to_f * 100
    @percent_complete = @percent_complete.to_i
   else
    @percent_complete = 0
   end
   
  end

  def edit
   @work_load = WorkLoad.find(params[:id])
  end

  def update
     @work_load = WorkLoad.find(params[:id])
    if @work_load.update_attributes(params[:work_load])
      flash[:notice] = "Successfully updated work load."
      redirect_to @work_load
    else
      render :action => 'edit'
    end
  end

  private

    def admin_user
     if current_user.admin?
      @work_load = WorkLoad.find(params[:id])
     else
       flash[:error] = "Not authorized to delete work load. Please contact an administrator"
       redirect_to workloads_path
     end
    end

    def authorized_user
     if current_user.admin? || current_user.manager?
      
     else
       flash[:error] = "Not authorized. Please contact an administrator"
       redirect_to work_loads_path
     end
    end

    def sort_column
      WorkLoad.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    def new_form_defaults
      @work_load.status = "Inactive"
      @work_load.probability = 0
      @work_load.impact = 0
    end

end

app/helpers/work_loads_helper.rb
module WorkLoadsHelper
end

app/views/work_loads/_form.html.erb
<%= simple_form_for @work_load do |f| %>
<%= f.input :requested_date, :label => 'Due Date' %>
<%= f.input :alias, :input_html => { :size => 15 }, :label => 'Code Name' %>
<%= f.association :contracts, :collection => Contract.all(:order => 'name') %>
<%= f.association :users, :collection => User.all(:order => 'name') %>
<%= f.input :name, :input_html => { :size => 30 }, :label => 'Display Name' %>
<%= f.input :description, :as => :text, :input_html => { :cols => 50, :rows => 4 } %>
<%= f.association :work_load_type, :collection => WorkLoadType.all(:order => 'name'), :label => 'Type of Work', :include_blank => false  %>
<%= f.input :impact, :input_html => { :size => 2, :value => 0 }, :collection => 0..5, :as => :radio, :label => 'Possible Impact', :hint => '5 is high' %>
<%= f.input :probability, :input_html => { :size => 2, :value => 0}, :collection => 0..5, :as => :radio, :label => 'Likelihood' %>
<%= f.input :status, :as => :radio, :collection => [["Inactive"],["Active"],["Closed"],["Cancelled"]] %>
<%= f.input :estimate, :input_html => { :size => 3 }, :hint => 'Measured in hours', :label => 'Effort Estimate' %>
<%= f.input :resolution_effort,  :input_html => { :size => 3, :disabled => true}, :label => 'Effort Expended' %> 
<%= f.input :expected_date %>
<% if @work_load.status == "Closed" || @work_load.status == "Cancelled" %>
<%= f.input :completed_date %>
<% end %>
<%= f.button :submit %>
<% end%>

app/views/work_loads/_show_assigned.html.erb
<table class="admin">
  <tr>
   <th><%= sortable "name" %></th>
   <th><%= sortable "status" %></th>
   <th><%= sortable "priority" %></th>
    <th><%= sortable "requested_date" %></th>
  </tr>
  <% for work_load in @work_loads %>
  <tr>
   <td><%= work_load.name %></td>
   <td><%= work_load.status %></td>
   <td><%= work_load.priority %></td>
   <td><%= work_load.requested_date %></td>
   <td><%= link_to icon("time"), new_work_load_work_history_path(work_load) %></td>
  </tr>
  <% end %>
</table>

app/views/work_loads/_work_loads.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table class="admin">
  <tr>
   <th><%= sortable "name" %></th>
   <th><%= sortable "status" %></th>
   <th><%= sortable "priority" %></th>
    <th><%= sortable "requested_date" %></th>
  </tr>
  <% for work_load in @work_loads %>
  <tr>
   <td><%= work_load.name %></td>
   <td><%= work_load.status %></td>
   <td><%= work_load.priority %></td>
   <td><%= work_load.requested_date %></td>
   <td>
   <%= link_to icon("view"), work_load %>
   <% if elevated_priv? %>
   <%= link_to icon("edit"), edit_work_load_path(work_load) %> | <%= link_to icon("delete"), work_load , :method => :delete , :confirm => 'Are you sure?'%> | 
   <% end %>
   <%= link_to icon("time"), new_work_load_work_history_path(work_load) %></td>
  </tr>
  <% end %>
</table>
<%= will_paginate @work_loads%>

app/views/work_loads/create.html.erb
<h1>WorkLoads#create</h1>
<p>Find me in app/views/work_loads/create.html.erb</p>

app/views/work_loads/destroy.html.erb
<h1>WorkLoads#destroy</h1>
<p>Find me in app/views/work_loads/destroy.html.erb</p>

app/views/work_loads/edit.html.erb
<%= render 'form' %>

<p>
  <%= link_to "Show", @work_load %> |
  <%= link_to "Delete", @work_load, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", work_loads_path %>
</p>

app/views/work_loads/index.html.erb
<%= form_tag work_loads_path, :method => 'get', :id => "work_loads_search" do %>
   
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <div id="work_loads"><%= render 'work_loads'%></div>
<% end %>




<p><%= link_to "New Work Load", new_work_load_path %></p>

app/views/work_loads/index.js.erb
$("#work_loads").html("<%= escape_javascript(render("work_loads")) %>")

app/views/work_loads/show.html.erb
<div class="showform">
   <div>
    <strong>Name:</strong>
    <%= @work_load.name %>
    (#<%= @work_load.alias %>)
  </div>
   <div>
   <strong><%= @work_load.status %> </strong>
   <%= @work_load.completed_date %>
    <strong>, Risk Factor:</strong>
    <%= @work_load.priority%> 
  </div>
  
  <div>
    <strong>Type of Work:</strong>
    <%= @work_load_type_name %>
  </div>
  <div>
    <strong>Description:</strong>
    <%= @work_load.description %>
  </div>
  <div>
    <strong>Affected Contracts:</strong>
    <% @work_load.contracts.each do |wc| %>
    <%= link_to wc.name, contract_path(wc) %> | 
    <%  end %>
  </div>
  <div>
    <strong>Assigned Users:</strong>
    <% @work_load.users.each do |wu| %>
    <%= link_to wu.name, user_path(wu) %> |
    <%  end %>
  </div>
  <div>
    <strong> Resolution hours:</strong>
    <%= @work_load.resolution_effort %> , <%= @percent_complete %> % complete
  </div>
  <div>
    <strong> Requested Completion Date:</strong>
    <%= @work_load.requested_date %>
  </div>
  <div>
    <strong> Projected Completion Date: </strong>
    <%= @work_load.expected_date %>
  </div>
    <%= link_to "Edit", edit_work_load_path(@work_load) %> |
    <%= link_to "View All", work_loads_path %>
  </div>
</div>

app/views/work_loads/update.html.erb
<h1>WorkLoads#update</h1>
<p>Find me in app/views/work_loads/update.html.erb</p>